ExternalProject_Add(${EP_NAME}
  PREFIX "${EP_PREFIX}"
  INSTALL_DIR "${CMAKE_BINARY_DIR}/install/x86_64"

  SOURCE_DIR "${CMAKE_SOURCE_DIR}/xhal"
  BUILD_ALWAYS TRUE
  CMAKE_ARGS
    "-DCMAKE_INSTALL_PREFIX=/usr"
    "-DCMAKE_PREFIX_PATH=${EP_INSTALL_DIR}/opt/xdaq/${XDAQ_PLATFORM}"
    "-DCMAKE_FIND_ROOT_PATH=${CMAKE_BINARY_DIR}/install/x86_64"
  INSTALL_COMMAND make install "DESTDIR=<INSTALL_DIR>"

  DEPENDS wiscrpcsvc-client.pc xdaq.pc
)

